blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/eclaire-labs/eclaire/security/advisories/new
    about: Please report security vulnerabilities privately here.
